language: C

dist: travis
sudo: required

env:
  global:
  - MAKEFLAGS=-j2
  - PYTHON=/usr/bin/python # avoid /opt/python

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y --no-install-recommends python-cairo python-imaging p7zip
- $PYTHON --version
- mkdir kindlegen
- wget -q -O - https://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz | tar -xz -C kindlegen
- export PATH=$PWD/kindlegen:$PATH

script:
- make jmdict.mobi

before_deploy:
- 7zr a jmdict-"$TRAVIS_TAG".7z jmdict.mobi

deploy:
  provider: releases
  api_key:
    secure: bmnrXL+vzUpUHeE6zuHXkLK7/7tpKo/tIhj/Ha8qWp0G0c4ySHlStGPKfbzaYmywCvXSDnGyPWAKncTv1cH4yRglWH/n53jhB9crGqcDdu+61JUwGerKFdAEs23xtfX1BtHD0qZ3HjQzGrFpHiebberLYUECnckfijXMNI/JBO0=
  file_glob: true
  file: jmdict-*.7z
  skip_cleanup: true
  on:
    repo: jrfonseca/jmdict-kindle
    tags: true
    all_branches: true
